fail_fast: true
repos:
- repo: local
  hooks:
    - id: mypy
      name: mypy
      entry: poetry run mypy
      language: system
      types: [file, python]
    - id: ruff
      name: ruff
      entry: poetry run ruff check && poetry run ruff format
      language: system
      types: [file, python]
