[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "python_project_cli"
version = "0.0.4"
authors = [
  { name="alexandermentormate", email="alexander.bozhkov@mentormate.com" },
]
description = "CLI for building base djang and fastapi based projects"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.pytest.ini_options]
pythonpath = "."
minversion = "6.0"
testpaths = [
    "tests",
]

[tool.mypy]
mypy_path = "src"
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = true

[tool.semantic_release]
version_variables = [
  "setup.py:__version__",
  "src/python_project_cli/__init__.py:__version__"
]
version_toml = ["pyproject.toml:project.version"]
major_on_zero = true
branch = "development"
upload_to_PyPI = true
upload_to_release = true
build_command = "python3 -m pip install build --user && python3 -m build"

# [tool.semantic_release]
# logging_use_named_masks = true
# tag_format = "v{version}"
# commit_parser = "angular"
# commit_author = "semantic-release <semantic-release>"
# commit_message = "{version}\n\nAutomatically generated by python-semantic-release"
# major_on_zero = true
# assets = []
# version_variables = ["src/python_project_cli/__init__.py:__version__"]
# version_toml = ["pyproject.toml:project.version"]

# [tool.semantic_release.branches.semantic-release]
# # match = "(main|master)"
# prerelease = false
# prerelease_token = "rc"

[project.urls]
Homepage = "https://github.com/MentorMate/python-project-cli"
